plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.lx.c_interface_library'
    compileSdk 34

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"



        buildConfigField "String","HOST","\"${rootProject.ext.appConfig["HOST"]}\""
        buildConfigField "String","PRIVATE_URL",  "\"${rootProject.ext.appConfig["privacyUrl"]}\""
        buildConfigField "String","USER_URL",  "\"${rootProject.ext.appConfig["userUrl"]}\""
        buildConfigField "String","RELEASE_APPID",  "\"${rootProject.ext.appConfig["RELEASE_APPID"]}\""
        buildConfigField "String","RELEASE_SSK",  "\"${rootProject.ext.appConfig["RELEASE_SSK"]}\""
        buildConfigField "boolean","LOGSWITCH",  "${rootProject.ext.appConfig["logSwitch"]}"
        buildConfigField "String","APPID",  "\"${rootProject.ext.appConfig["APPID"]}\""
        buildConfigField "String","FISRT_SPLASH",  "\"${rootProject.ext.appConfig["FISRT_SPLASH"]}\""
        buildConfigField "String","VERSIONNAME",  "\"${rootProject.ext.appConfig["VERSIONNAME"]}\""
        buildConfigField "String","UM_ID",  "\"${rootProject.ext.appConfig["umID"]}\""
        buildConfigField "String","AD_LIVE_TIME",  "\"${rootProject.ext.appConfig["ad_LiveTime"]}\""
        buildConfigField "String","JL_APPID",  "\"${rootProject.ext.appConfig["JL_APPID"]}\""


    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '18'
    }


    viewBinding {
        enabled = true
    }

    buildFeatures {
        buildConfig = true
    }


}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
}